services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  alloy:
    image: grafana/alloy:latest
    pull_policy: always
    restart: on-failure
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
      # - --stability.level=experimental # Enable all functionality
    environment:
      GRAFANA_CLOUD_OTLP_ENDPOINT: ${GRAFANA_CLOUD_OTLP_ENDPOINT}
      GRAFANA_CLOUD_INSTANCE_ID: ${GRAFANA_CLOUD_INSTANCE_ID}
      GRAFANA_CLOUD_API_KEY: ${GRAFANA_CLOUD_API_KEY}
    ports:
      - "4317:4317"
      - "4318:4318"
      - "12345:12345"
      